default:
  image: registry.gitlab.com/splash07/ubuntu-ansible/ubuntu-ansible
  
  before_script:
    - whoami
    - apt-get update -qy
    - ansible --version
    - ansible-lint --version
    - echo "$ANSIBLE_SSHKEY" > .ssh/id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False

stages:
  #- verify
  - predeploy
  - deploy

#ansible-verify:
#  stage: verify
#  script:
#    - ansible-lint -v *.yml
#    - ansilble-playbook --syntax-check *.yml
#  rules:
#    - if: '$CI_BUILD_BEFORE_SHA == "0000000000000000000000000000000000000000"'
#      when: always
#    - if: '$CI_COMMIT_BRANCH != "master"'
#      when: always

predeploy:
  stage: predeploy
  script:
    - ansible all -m ping -i inventory.yml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always

deploy:
  stage: deploy
  script:
    - ./cicd-info.sh > roles/common/files/cicd-info.txt # Run script to get GitLab CI env vars. Ansible will copy then to hosts.
    - ansible-playbook -i inventory.yml --user ansible playbook.yml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
