---
- hosts: proxy
  become: true
  gather_facts: no

  tasks:
    #- name: Copy to .tmp folder (what to copy?)
    - name: Create a backup folder for current nginx configs
      file:
        path: /tmp/nginx-conf-backup
        state: directory
    
    - name: Copy current nginx configs to backup folder
      shell: 'cp -r /etc/nginx/conf.d/ /tmp/nginx-conf-backup'

    - name: Remove current nginx configs in config.d
      find:
        paths: /etc/nginx/conf.d
        patterns: "*.conf"
        use_regex: true
      register: wildcard_files_to_delete


    - name: Install alls configs for nginx
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - "{ src: conf/project.conf.j2, dest: /etc/nginx/conf.d/project.conf }"
      
    - name: Reload nginx to activate specified site
      service: name=nginx state=restarted
